apiVersion: v1
name: cubepaas-bs
version: 0.8.3
appVersion: v0.8.0
kubeVersion: ">=v1.14.0-r0"
description: cubepaasBS is a distributed block storage system for Kubernetes.
keywords:
- cubepaasBS
- storage
- distributed
- block
- device
- iscsi