apiVersion: apps/v1
kind: Deployment
metadata:
  name: storagebs-driver-deployer
  namespace: {{ .Release.Namespace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: storagebs-driver-deployer
  template:
    metadata:
      labels:
        app: storagebs-driver-deployer
    spec:
      initContainers:
        - name: wait-storagebs-manager
          image: "{{ template "system_default_registry" . }}{{ .Values.image.storagebs.manager }}:{{ .Values.image.storagebs.managerTag }}"
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://storagebs-backend:9500/v1) != "200" ]; do echo waiting; sleep 2; done']
      containers:
        - name: storagebs-driver-deployer
          image: "{{ template "system_default_registry" . }}{{ .Values.image.storagebs.manager }}:{{ .Values.image.storagebs.managerTag }}"
          imagePullPolicy: Always
          command:
          - longhorn-manager
          - -d
          - deploy-driver
          - --manager-image
          - "{{ template "system_default_registry" . }}{{ .Values.image.storagebs.manager }}:{{ .Values.image.storagebs.managerTag }}"
          - --manager-url
          - http://storagebs-backend:9500/v1
          env:
          - name: POD_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          - name: NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: SERVICE_ACCOUNT
            valueFrom:
              fieldRef:
                fieldPath: spec.serviceAccountName
          {{- if .Values.csi.kubeletRootDir }}
          - name: KUBELET_ROOT_DIR
            value: {{ .Values.csi.kubeletRootDir }}
          {{- end }}
          {{- if .Values.csi.attacherImage }}
          - name: CSI_ATTACHER_IMAGE
            value: {{ template "system_default_registry" . }}{{ .Values.csi.attacherImage }}
          {{- end }}
          {{- if .Values.csi.provisionerImage }}
          - name: CSI_PROVISIONER_IMAGE
            value: {{ template "system_default_registry" . }}{{ .Values.csi.provisionerImage }}
          {{- end }}
          {{- if .Values.csi.nodeDriverRegistrarImage }}
          - name: CSI_NODE_DRIVER_REGISTRAR_IMAGE
            value: {{ template "system_default_registry" . }}{{ .Values.csi.nodeDriverRegistrarImage }}
          {{- end }}
          {{- if .Values.csi.resizerImage }}
          - name: CSI_RESIZER_IMAGE
            value: {{ template "system_default_registry" . }}{{ .Values.csi.resizerImage }}
          {{- end }}
          {{- if .Values.csi.attacherReplicaCount }}
          - name: CSI_ATTACHER_REPLICA_COUNT
            value: "{{ .Values.csi.attacherReplicaCount | quote }}"
          {{- end }}
          {{- if .Values.csi.provisionerReplicaCount }}
          - name: CSI_PROVISIONER_REPLICA_COUNT
            value: "{{ .Values.csi.provisionerReplicaCount | quote }}"
          {{- end }}
          {{- if .Values.csi.resizerReplicaCount }}
          - name: CSI_RESIZER_REPLICA_COUNT
            value: {{ .Values.csi.resizerReplicaCount | quote }}
          {{- end }}
          resources:
            limits:
              cpu: {{ .Values.resources.manager.limits.cpu }}
              memory: {{ .Values.resources.manager.limits.memory }}
            requests:
              cpu: {{ .Values.resources.manager.requests.cpu }}
              memory: {{ .Values.resources.manager.requests.cpu }}
      {{- if .Values.defaultSettings.registrySecret }}
      imagePullSecrets:
      - name: {{ .Values.defaultSettings.registrySecret }}
      {{- end }}
      serviceAccountName: storagebs-service-account
      securityContext:
        runAsUser: 0
