apiVersion: v1
description: Provides monitoring for Kubernetes which maintaining by cubepaas 2.
engine: gotpl
maintainers:
name: cubepaas-monitoring
sources:
- https://github.com/coreos/prometheus-operator
version: 0.0.2
appVersion: 0.0.2
home: https://github.com/coreos/prometheus-operator
keywords:
- operator
- prometheus
icon: https://link-cloud.oss-cn-hangzhou.aliyuncs.com/monit.png
